# Generated by Django 4.2 on 2025-01-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../default_profile_iy5ppe', upload_to='images/'),
        ),
    ]
